config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'  
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'categories/:id/products', to: 'categories#products', as: 'categories_products'


  resources :categories 
  resources :products

  resources :customers, only: [:new, :create]
  get 'login', to: 'customers#login_form'
  post 'login', to: 'customers#login'
  get '/signup', to: 'customers#new', as: :signup
  get '/customers', to: 'customers#create', as: :create_customer
  get 'logout', to: 'customers#logout'

  get '/cart', to: 'carts#index'

  get '/products/add_to_cart/:id', to: 'products#add_to_cart', as: :add_to_cart
  delete '/products/remove_from_cart/:id', to: 'products#remove_from_cart', as: :remove_from_cart
  get '/products/update_quantity/:id', to: 'products#update_quantity', as: :update_quantity_product

  get '/customers/:id/update_address', to: 'customers#update_address', as: :update_address

  get '/orders/address', to: 'orders#non_logged_in_address', as: :non_user_address
  get '/change_address', to: 'orders#change_address', as: 'change_address'


  post '/checkout', to: 'orders#checkout', as: 'checkout'
  get '/orders/index', to: 'orders#index', as: 'invoice'

  get '/non_user_proceed_to_payment', to: 'orders#non_user_proceed_to_payment', as: :non_user_proceed_to_payment
  get '/proceed_to_payment', to: 'orders#proceed_to_payment', as: :proceed_to_payment
  get '/order_success/:id', to: 'orders#order_success', as: :order_success
  get '/order_cancel/:id', to: 'orders#order_cancel', as: :order_cancel

  get '/my_profile', to: 'customers#show', as: 'my_profile'

  resources :contact_pages, only: [:show]
  resources :about_pages, only: [:show]

  
end

app/models/about_page.rb
class AboutPage < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true

    def self.ransackable_attributes(auth_object = nil)
        ["content", "created_at", "id", "title", "updated_at"]
      end
  end
  

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
        end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    def self.ransackable_attributes(auth_object = nil)
        ["id", "name", "description", "created_at", "updated_at"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["products"]
    end
end

app/models/contact_page.rb
class ContactPage < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true

    def self.ransackable_attributes(auth_object = nil)
        ["content", "created_at", "id", "title", "updated_at"]
      end
  end
  

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders
  has_secure_password
  validates :first_name, :last_name, :email, :phone, :address, :city, :postal_code, presence: true
  validates :first_name, :last_name, length: { maximum: 50 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, format: { with: /\A[\d\+\-\(\)]+\z/, message: "only allows digits, +, -, (, and )" }
  validates :email, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][ -]?\d[ABCEGHJ-NPRSTV-Z]\d\z/i }

  def self.ransackable_attributes(auth_object = nil)
    ["address", "city", "created_at", "email", "first_name", "id", "last_name", "phone", "postal_code", "province_id", "updated_at", "password_digest"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["province", "orders"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :province
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :customer_id, presence: true
  validates :total_price, numericality: { greater_than_or_equal_to: 0 }

  def self.ransackable_attributes(auth_object = nil)
    ["id", "customer_id", "total_price","status","tax", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["customer", "order_items", "products"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order_id, :product_id, :quantity, :cost, presence: true
  validates :quantity, numericality: { greater_than: 0 }
  validates :cost, numericality: { greater_than_or_equal_to: 0 }

  def self.ransackable_attributes(auth_object = nil)
    ["cost", "created_at", "id", "order_id", "product_id", "quantity", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  belongs_to :category

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_status, inclusion: { in: ['yes', 'no'] }
  validates :category, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "name", "price", "sale_status", "stock", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_items", "orders"]
  end
end

app/models/province.rb
# app/models/province.rb

class Province < ApplicationRecord  
    has_many :orders
    # Validations
    validates :name, presence: true, uniqueness: true
    validates :pst, :hst, :gst, :applicable, presence: true, numericality: { greater_than_or_equal_to: 0 }
  
    def self.ransackable_attributes(auth_object = nil)
      ["id", "name", "pst", "hst", "gst", "applicable"]
    end
    def self.ransackable_associations(auth_object = nil)
      ["orders"]
    end
  end
  

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :initialize_cart_session
    before_action :load_cart

    def index
        cart_ids = session[:cart].map { |item| item["id"] }
        @cart_items = Product.where(id: cart_ids)
      end

    def add_to_cart
        id = params[:id].to_i  
        session[:cart] << id unless session[:cart].include?(id)
        redirect_to products_path
    end

    def remove_cart
        id = params[:id].to_i  
        session[:cart].delete(id)
        redirect_to products_path
    end

    def update_quantity
        product_id = params[:product_id].to_i
        quantity = params[:quantity].to_i
        cart_item = session[:cart].find { |item| item["id"] == product_id }
        
        if cart_item
          cart_item["quantity"] = quantity
          flash[:notice] = "Quantity updated successfully."
        else
          flash[:error] = "Product not found in the cart."
        end
    
        redirect_to carts_path
      end
    
    private

    def initialize_cart_session
        session[:cart] ||= []
    end
    
    def load_cart
        cart_ids = session[:cart].map { |item| item["id"] }
        products = Product.where(id: cart_ids)
        @cart = products.each_with_object([]) do |product, cart_items|
          cart_item = session[:cart].find { |item| item["id"] == product.id }
          quantity = cart_item["quantity"] if cart_item
          cart_items << { product: product, quantity: quantity || 0 }
        end
      end
      
      
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>WinnipegSportsEmporium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
      const stripe = Stripe("pk_test_51NaaAfDhG2kZYzC2LKWsmnqf3mI8fwYdJTX0WCdcQyTeCmEKwB2mLrbLZqo6svRNKdHEhE4VYFQzAmf45RUCkm5R00TTsfbHC4");
    </script>
  </head>

  <body>
    <div id="content">
    <%= render 'shared/menu' %>
    <%= yield %>
    
    <% flash.each do |key, value| %>
      <div class="text-center flash-<%= key %>"><%= value %></div>
    <% end %>

    <%= render 'shared/footer' %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.name.downcase %> from being saved:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <hr>
    <div class="container ">
        <div class="row d-flex" >
            <div class="col-4">
                <ul class="list-inline ">
                    <li class="list-inline-item "><a href="<%= root_path %>" class="link-primary text-decoration-none">Home</a></li>
                    <li class="list-inline-item"><a href="<%= about_path %>" class="link-primary text-decoration-none">About</a></li>
                    <li class="list-inline-item"><a href="<%= contact_path %>" class="link-primary text-decoration-none">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-4 d-flex justify-content-center ">
                <p>Md Mahamudun Alam Mahin</p>
            </div>
            <div class="col-4 d-flex justify-content-end">
                <p>&copy; 2023 WSE. All rights reserved.</p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>" style="text-decoration: none;">WinnipegSportsEmporium</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>" style="text-decoration: none;">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= products_path %>" style="text-decoration: none;">Products</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="<%= categories_path %>" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="text-decoration: none;">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% @product_categories.each do |category| %>
            <li>
            <a class="dropdown-item" href="<%= categories_products_path(category) %>" style="text-decoration: none;"><%= category.name %></a>
            </li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= cart_path %>" style="text-decoration: none;">Cart</a>
        </li>
        <li class="nav-item">
        <% if logged_in? %>
          <a class="nav-link" href="<%= logout_path %>" style="text-decoration: none;">Log-out</a>
        <% else %>
          <a class="nav-link" href="<%= login_path %>" style="text-decoration: none;">Log-in</a>
        <% end %>
        </li>
        <% if logged_in? %>
        <li class="nav-item">
            <a class="nav-link" href="<%= my_profile_path %>" style="text-decoration: none;">My Profile</a>
        </li>
        <% end %>
      </ul>
      <form class="d-flex" method="GET" action="<%= products_path %>">
        <select class="form-select" name="category_id" aria-label="Default select example">
            <option value="">All</option>
            <% @product_categories.each do |category| %>
            <option value="<%= category.id %>"><%= category.name %></option>
            <% end %>
        </select>
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success text-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_non_user_address_form.html.erb
<%= form_with url: non_user_address_path, method: :get, class: 'needs-validation', novalidate: true do |form| %>
  <div class="mb-3">
    <%= form.label :address, class: 'form-label' %>
    <%= form.text_field :address, class: 'form-control', required: true %>
  </div>
  <div class="mb-3">
    <%= form.label :city, class: 'form-label' %>
    <%= form.text_field :city, class: 'form-control', required: true %>
  </div>
  <div class="mb-3">
    <%= form.label :postal_code, class: 'form-label' %>
    <%= form.text_field :postal_code, class: 'form-control', required: true %>
  </div>
  <div class="mb-3">
    <%= form.label :province_id, class: 'form-label' %>
    <%= form.select :province_id, options_for_select(Province.all.map { |province| [province.name, province.id] }), { prompt: 'Select Province', class: 'form-select', required: true } %>
  </div>
  <div class="mb-3">
    <%= form.submit "Save Address", class: 'btn btn-primary' %>
  </div>
<% end %>