config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'  
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'categories/:id/products', to: 'categories#products', as: 'categories_products'


  resources :categories 
  resources :products

  resources :customers, only: [:new, :create]
  get 'login', to: 'customers#login_form'
  post 'login', to: 'customers#login'
  get '/signup', to: 'customers#new', as: :signup
  get '/customers', to: 'customers#create', as: :create_customer
  get 'logout', to: 'customers#logout'

  get '/cart', to: 'carts#index'

  get '/products/add_to_cart/:id', to: 'products#add_to_cart', as: :add_to_cart
  delete '/products/remove_from_cart/:id', to: 'products#remove_from_cart', as: :remove_from_cart
  get '/products/update_quantity/:id', to: 'products#update_quantity', as: :update_quantity_product

  get '/customers/:id/update_address', to: 'customers#update_address', as: :update_address

  get '/orders/address', to: 'orders#non_logged_in_address', as: :non_user_address
  get '/change_address', to: 'orders#change_address', as: 'change_address'


  post '/checkout', to: 'orders#checkout', as: 'checkout'
  get '/orders/index', to: 'orders#index', as: 'invoice'

  get '/non_user_proceed_to_payment', to: 'orders#non_user_proceed_to_payment', as: :non_user_proceed_to_payment
  get '/proceed_to_payment', to: 'orders#proceed_to_payment', as: :proceed_to_payment
  get '/order_success/:id', to: 'orders#order_success', as: :order_success
  get '/order_cancel/:id', to: 'orders#order_cancel', as: :order_cancel

  get '/my_profile', to: 'customers#show', as: 'my_profile'

  resources :contact_pages, only: [:show]
  resources :about_pages, only: [:show]

  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :initialize_cart_session
    before_action :load_cart

    def index
        cart_ids = session[:cart].map { |item| item["id"] }
        @cart_items = Product.where(id: cart_ids)
      end

    def add_to_cart
        id = params[:id].to_i  
        session[:cart] << id unless session[:cart].include?(id)
        redirect_to products_path
    end

    def remove_cart
        id = params[:id].to_i  
        session[:cart].delete(id)
        redirect_to products_path
    end

    def update_quantity
        product_id = params[:product_id].to_i
        quantity = params[:quantity].to_i
        cart_item = session[:cart].find { |item| item["id"] == product_id }
        
        if cart_item
          cart_item["quantity"] = quantity
          flash[:notice] = "Quantity updated successfully."
        else
          flash[:error] = "Product not found in the cart."
        end
    
        redirect_to carts_path
      end
    
    private

    def initialize_cart_session
        session[:cart] ||= []
    end
    
    def load_cart
        cart_ids = session[:cart].map { |item| item["id"] }
        products = Product.where(id: cart_ids)
        @cart = products.each_with_object([]) do |product, cart_items|
          cart_item = session[:cart].find { |item| item["id"] == product.id }
          quantity = cart_item["quantity"] if cart_item
          cart_items << { product: product, quantity: quantity || 0 }
        end
      end
      
      
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="container mt-5">
  <h1>Cart</h1>
  <% if @cart.empty? %>
    <p>Your cart is empty.</p>
  <% else %>
    <ul class="list-group">
      <% @cart.each do |cart_item| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div>
            <%= "#{cart_item[:product].name} - #{cart_item[:quantity]}" %>
          </div>
          <div class="d-flex align-items-center">
            <%= form_with url: update_quantity_product_path(cart_item[:product].id), method: :get, class: 'form-inline' do |form| %>
              <div class="input-group">
                <%= form.number_field :quantity, min: 1, class: 'form-control', id: "quantity_#{cart_item[:product].id}" %>
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </div>
            <% end %>
            <form action="<%= remove_from_cart_path(cart_item[:product].id) %>" method="post" class="form-inline ml-3">
              <input type="hidden" name="_method" value="delete" />
              <button type="submit" class="btn btn-danger">Remove</button>
            </form>
          </div>
        </li>
      <% end %>
    </ul>

    <div class="d-flex justify-content-end mt-3 mx-4">
      <%= form_tag invoice_path, method: :get do %>
        <%= submit_tag "Checkout", class: 'btn btn-success' %>
      <% end %>
    </div>
  <% end %>
</div>