config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'  
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'categories/:id/products', to: 'categories#products', as: 'categories_products'


  resources :categories 
  resources :products

  resources :customers, only: [:new, :create]
  get 'login', to: 'customers#login_form'
  post 'login', to: 'customers#login'
  get '/signup', to: 'customers#new', as: :signup
  get '/customers', to: 'customers#create', as: :create_customer
  get 'logout', to: 'customers#logout'

  get '/cart', to: 'carts#index'

  get '/products/add_to_cart/:id', to: 'products#add_to_cart', as: :add_to_cart
  delete '/products/remove_from_cart/:id', to: 'products#remove_from_cart', as: :remove_from_cart
  get '/products/update_quantity/:id', to: 'products#update_quantity', as: :update_quantity_product

  get '/customers/:id/update_address', to: 'customers#update_address', as: :update_address

  get '/orders/address', to: 'orders#non_logged_in_address', as: :non_user_address
  get '/change_address', to: 'orders#change_address', as: 'change_address'


  post '/checkout', to: 'orders#checkout', as: 'checkout'
  get '/orders/index', to: 'orders#index', as: 'invoice'

  get '/non_user_proceed_to_payment', to: 'orders#non_user_proceed_to_payment', as: :non_user_proceed_to_payment
  get '/proceed_to_payment', to: 'orders#proceed_to_payment', as: :proceed_to_payment
  get '/order_success/:id', to: 'orders#order_success', as: :order_success
  get '/order_cancel/:id', to: 'orders#order_cancel', as: :order_cancel

  get '/my_profile', to: 'customers#show', as: 'my_profile'

  resources :contact_pages, only: [:show]
  resources :about_pages, only: [:show]

  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    def self.ransackable_attributes(auth_object = nil)
        ["id", "name", "description", "created_at", "updated_at"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["products"]
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :initialize_cart_session
  before_action :load_cart
  def index
    @categories = Category.page(params[:page]).per(10)
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(10)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted.'
  end

  def products
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(10)
  
    render 'products', locals: { products: @products }
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
  def initialize_cart_session
    session[:cart] ||= []
  end

  def load_cart
    cart_ids = session[:cart].map { |item| item["id"] }
    @cart = Product.where(id: cart_ids)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/products.html.erb
<h2 class="text-center">All Products <strong>(<%= @category.name %>)</strong></h2>

<div class="row">
  <div class="col-12 mx-2">
    <ul class="list-group">
      <li class="list-group-item">
        <p class="text-center text-light bg-dark m-0">To see more information about a product, simply click on its name.</p>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <strong>ID | Products</strong>
          <strong style="display: none;">nothing</strong>
          <strong class="text-center mx-2">Cart-Action</strong>
        </div>
      </li>
      <% if @products.present? %>
        <% @products.each do |product| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= link_to product_path(product), class: 'text-decoration-none text-dark' do %>
              <%= product.id %> | <%= product.name %>
            <% end %>
            
            <div class="btn-group">
              <% if @cart.include?(product) %>
                <span class="badge bg-success d-flex align-items-center justify-content-center mb-2">Product is in your cart</span>
                <%= form_with url: remove_from_cart_path(product.id), method: :delete, class: 'form-inline' do |form| %>
                  <button type="submit" class="btn btn-danger btn-sm mr-4">Remove from cart</button>
                <% end %>
              <% else %>
                <%= form_with url: add_to_cart_path(product.id), method: :get, class: 'form-inline' do |form| %>
                  <div class="input-group">
                    <%= form.number_field :quantity, min: 1, class: 'form-control', required: true, id: "quantity_#{product.id}" %>
                    <button type="submit" class="btn btn-primary">Add to cart</button>
                  </div>
                <% end %>
              <% end %>
            </div>
          </li>
        <% end %>
      <% else %>
        <li class="list-group-item text-center">No products found.</li>
      <% end %>
    </ul>
  </div>
</div>

<div class="my-5">
  <%= paginate @products %>
</div>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->
<h1><%= @category.name %> Products</h1>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

<%= paginate @products %>